name: YaizuSample Linux CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v1
    - name: exec build
      run: |
        git clone -q --branch=master https://github.com/s-takeuchi/YaizuComLib.git ../YaizuComLib
        git checkout master
        cd build
        ./build_cen64_svr.sh
        ./build_cen64_agt.sh
    - name: exec test
      run: |
        cd build
        ./test.sh
